module.exports = {
    product:[
        {
            id: 1000101,
            name: '弹性云主机',
            describe: '一种可随时获取、弹性可扩展的计算服务。云主机由 CPU、内存、镜像、云硬盘组成，同时结合VPC、安全组、数据多副本保存等能力，打造一个既高效又可靠安全的计算环境，确保服务持久稳定运行。',
            usageCount: 7,
            hostsNumber: 10.21,
            addhostsNumber:80.21,
            checked1:true,
            checked2:false,
        },
        {
            id: 1000102,
            name: '对象存储OOS',
            describe:"专门针对云计算、大数据和非结构化数据的海量存储形态，通过标准的服务接口，提供非结构化数据（图片、音视频、文本等格式文件）的无限存储服务。",
            usageCount: 7,
            hostsNumber: 88.21,
            addhostsNumber:80.21,
            checked1:false,
            checked2:false,
        },
        {
            id: 1000103,
            name: '弹性负载均衡ELB',
            describe:"通过将访问流量自动分发到多台云主机，扩展应用系统对外的服务能力，解决大并发访问服务器的问题，实现更高水平的应用程序容错性能。",
            usageCount: 7,
            hostsNumber: 88.21,
            addhostsNumber:80.21,
            checked1:false,
            checked2:false,
        },
        {
            id: 1000104,
            name: '关系数据库MySQL',
            describe:"基于云计算平台的在线关系型数据库服务，完全兼容MySQL 5.6、MySQL 5.7，提供单机、主备、只读三种实例类型，提供备份、恢复、扩容、监控等数据库服务。",
            usageCount: 7,
            hostsNumber: 88.21,
            addhostsNumber:80.21,
            checked1:false,
            checked2:false,
        },
        {
            id: 1000105,
            name: 'CDN内容分发',
            describe:"将源站大文件内容分发至最接近用户的节点，使用户可就近获取所需内容。适用于游戏安装包获取、手机ROM升级、应用程序包下载等业务场景，为用户提供稳定、优质的下载加速服务。",
            usageCount: 7,
            hostsNumber: 88.21,
            addhostsNumber:80.21,
            checked1:false,
            checked2:false,
        },
        {
            id: 1000106,
            name: 'GPU云主机',
            describe:"基于GPU的应用于视频解码、图形渲染、深度学习、科学计算等多种场景的计算服务。天翼云GPU云主机采用业界先进的GPU硬件，让客户得到极致性能体验的同时，获得最佳性价比。目前提供图形加速型（G系列）和计算加速型（P系列）两类GPU云主机。",
            usageCount: 7,
            hostsNumber: 88.21,
            addhostsNumber:80.21,
            checked1:false,
            checked2:false,
        },
        {
            id: 1000107,
            name: '物理机',
            describe:"提供资源独享、安全可靠的云上物理机服务器。卓越的计算、存储性能，满足核心数据库等应用需求。同时，可实现物理机和云主机混合组网，灵活部署应对各种业务场景",
            usageCount: 7,
            hostsNumber: 88.21,
            addhostsNumber:80.21,
            checked1:false,
            checked2:false,
        },
        {
            id: 1000108,
            name: '云存储网关',
            describe:"为客户提供高可靠的跨资源池云主机高速互联；云间高速产品可实现资源池间高速、稳定、安全、灵活的私网通信，客户一点上云，云间互联，并支持提供点到点、点到多点和网状拓扑的IP互联。",
            usageCount: 7,
            hostsNumber: 88.21,
            addhostsNumber:80.21,
            checked1:false,
            checked2:false,
        },
        {
            id: 1000109,
            name: '云专线CDA',
            describe:"基于中国电信网络基础资源及服务能力，为用户提供自有IT环境（私有云）与云资源之间安全、可靠、统一的专线或专网服务。",
            usageCount: 7,
            hostsNumber: 88.21,
            addhostsNumber:80.21,
            checked1:false,
            checked2:false,
        }
    ]
}